apiVersion: v1
kind: Service
metadata:
  name: upf-service
  namespace: test
  labels:
    nf: upf
spec:
  ports:
  - name: metrics # expose metrics port
    port: 9000 # defined in upf chart
    targetPort: metrics  # port name in pod
  selector:
    nf: upf # target upf pods
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: upf-servicemonitor
  # Change this to the namespace the Prometheus instance is running in
  namespace: monitoring
  labels:
    nf: upf
spec:
  namespaceSelector:
    any: true  # important otherwise this is not picked up
  selector:
    matchLabels:
      nf: upf # target upf service
  endpoints:
  - port: metrics
    interval: 3s
