apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: 
  labels:
    app.kubernetes.io/name: mongodb
spec:
  type: ClusterIP
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
      nodePort: null
  selector:
    app.kubernetes.io/name: mongodb
