---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 5gnetwork
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eno1",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "subnet": "192.168.10.0/27",
        "exclude": [ "192.168.10.1/27" ],
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.10.1"
      }
    }'
