---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-ue
  labels:
    app: ueransim
    component: ue
spec:
  selector:
    matchLabels:
      app: ueransim
      component: ue
  replicas: 
  template:
    metadata:
      labels:
        app: ueransim
        component: ue
    spec:
      containers:
      - image: ghcr.io/niloysh/ueransim:v3.2.6
        name: ue
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - mountPath: /ueransim/config
          name: ue-volume
        resources:
          requests:
            memory: "128Mi"
            cpu: "120m"
          limits:
            memory: "128Mi"
            cpu: "120m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: ue-volume
        configMap:
          name: ue-configmap
          items:
          - key: free5gc-ue.yaml
            path: free5gc-ue.yaml
          - key: free5gc-ue2.yaml
            path: free5gc-ue2.yaml
          - key: wrapper.sh
            path: wrapper.sh
            mode: 0755
