apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../free5gc

resources:
  - smf2
  - upf2

configMapGenerator:
- name: amf-configmap
  behavior: replace
  files:
    - configs/amfcfg.yaml
- name: nssf-configmap
  behavior: replace
  files:
    - configs/nssfcfg.yaml