---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-gnb
  labels:
    app: ueransim
    component: gnb
spec:
  selector:
    matchLabels:
      app: ueransim
      component: gnb
  replicas: 
  template:
    metadata:
      labels:
        app: ueransim
        component: gnb
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "5gnetwork", "interface": "n3", "ips": [ "129.97.168.131/24" ] },
          { "name": "5gnetwork", "interface": "n2", "ips": [ "129.97.168.141/24" ] }
          ]'
    spec:
      containers:
      - image: ghcr.io/niloysh/ueransim:v3.2.6
        name: gnb
        ports:
        - name: gnb-ue
          containerPort: 4997
          protocol: UDP
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - mountPath: /ueransim/config
          name: gnb-volume
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: gnb-volume
        configMap:
          name: gnb-configmap
