apiVersion: v1
kind: Service
metadata:
  name: kpi-exporter-service
  namespace: test
  labels:
    app: kpi-exporter
spec:
  ports:
  - name: metrics # expose metrics port
    port: 9000 # defined in chart
    targetPort: metrics  # port name in pod
  selector:
    app: kpi-exporter # target pods
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kpi-exporter-servicemonitor
  # Change this to the namespace the Prometheus instance is running in
  namespace: monitoring
  labels:
    app: kpi-exporter
spec:
  namespaceSelector:
    any: true  # important otherwise this is not picked up
  selector:
    matchLabels:
      app: kpi-exporter # target upf service
  endpoints:
  - port: metrics
    interval: 1s