apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpi-exporter
  namespace: test
  labels:
    app: kpi-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpi-exporter
  template:
    metadata:
      labels:
        app: kpi-exporter
    spec:
      containers:
      - name: kpi-exporter
        image: ghcr.io/niloysh/kpi-exporter:v1.1.0
        imagePullPolicy: Always
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - name: metrics
          containerPort: 9000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
      restartPolicy: Always
