---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpi-exporter
  namespace: test
  labels:
    app: kpi-exporter
spec:
  selector:
    matchLabels:
      app: kpi-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: kpi-exporter
    spec:
      containers:
      
      - image: ghcr.io/niloysh/kpi-exporter:v1.1.0
        name: kpi-exporter
        imagePullPolicy: Always
        ports:
        - name: metrics
          containerPort: 9000

        # command: [ "/bin/bash", "-c", "--" ]
        # args: [ "python -u kpi-exporter.py" ]

        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]

      restartPolicy: Always
